### ISSUE TITLE
[Issue] Factorio 1.0 update

### ISSUE THREAD

**Issue by jeremybris** [FactorioBlueprints/factorio-prints#241]
I can not upload blueprints that are very long/big. See my page for examples. Great website other than that :).

My name is Yoyo Ma on factorioprints.com. https://factorioprints.com/user/lEPYdC58rvhWCgVGvgeoUBREKXf2

**Comment by Bocian-1** [comment]
I don't think it's the length. I've been able to successfully upload a string that is nearly 6 times longer than your updated Power Book. https://raw.githubusercontent.com/Bocian-1/10-Books-Full-of-Rails/master/Blueprint%20String
It didn't go without any issues tho (#240). Since you've updated your book on 15th, which is before my issue has been resolved (21st), it's possible that you've had the same problem as I did. If so, it should work now.

**Comment by jeremybris** [comment]
@Bocian-1, pardon me, the issue has been fixed since I last tried. Thank you for your comment. Closing.
